### ISSUE TITLE
Enhance the Stock Display Page with Categories and Read More Functionality

### ISSUE THREAD

**Issue by AyushKumar123456789** [AyushKumar123456789/stock-analysis-frontend#14]
**Description:**
Enhance the `stocks` file to display blog posts in a structured manner, similar to the provided image. The page should display the date/category and title of each post, with category filters at the top for easy navigation which is formed by differnet type of categories of blogs. Each post should include a "Read More" button for accessing the full content.

**Tasks:**

1. **UI Enhancements:**
   - Design a table or list to display the date/category and title of each blog post.
   - Include a "Read More" button next to each post for accessing the full content.
   - Implement CSS to ensure the layout matches the provided design.

2. **Category Filters:**
   - Display all available blog categories at the top of the page as filter buttons.
   - Ensure that clicking on a category filter displays only the posts belonging to that category.

3. **Backend Integration:**
   - Fetch the blog posts from the backend, including their categories, dates, titles, and content.
   - Implement functionality to filter posts based on the selected category.

4. **Read More Functionality:**
   - Implement the "Read More" button to navigate to the full post view or expand the content within the same page.
   - Ensure that the full content is fetched and displayed correctly.

**Acceptance Criteria:**
- The `stocks` page displays blog posts with date/category, title, and a "Read More" button.
- Category filters are displayed at the top, allowing users to filter posts by category.
- The "Read More" button works correctly, displaying the full content of the post.
- The design matches the provided image in terms of layout and style.

**Additional Notes:**
- Ensure that the design is responsive and looks good on both desktop and mobile devices.
- Follow the existing coding standards and practices used in the project.
- The `stocks` file is located in the `components/Stocks/Stocks.js` file.

If you have any questions or need further clarification, please feel free to ask.
Editor Login Details:

Email: [stockanalysistest899@gmail.com](mailto:stockanalysistest899@gmail.com)
Password: 12345678
Role: Editor

**Comment by Dheeraj4103** [comment]
Hey @AyushKumar123456789 can I work on this issue ?

**Comment by AyushKumar123456789** [comment]
Yes, Sure

**Comment by Dheeraj4103** [comment]
Can I get Backend endpoints to display stocks

**Comment by AyushKumar123456789** [comment]
You have to clone the backend part of this project also, https://github.com/AyushKumar123456789/stock-analysis-backend, and for the stock display endpoint you can look at this: https://github.com/AyushKumar123456789/stock-analysis-backend/blob/5bc2a96e10271e6c9e5de277bb25a780ed44ffc9/controllers/stockController.js

I hope this helps,
If you have any questions or need further clarification, please feel free to ask.
Thank you

**Comment by Dheeraj4103** [comment]
Thanks

**Comment by Dheeraj4103** [comment]
Hey @AyushKumar123456789 I have created a pull request for this issue.
Could you please check it out and let me know if there are some issues.
